- name: Deploy a web application
  hosts: db_and_web_server1,db_and_web_server2
  roles:
    - python
    - mysql_db
    - flask_web



   

   # - include_tasks: tasks/deploy_db.yaml
   # - include_tasks: tasks/deploy_web.yaml